export default function Page() {
  return <main>
    <header className="nav"><div className="wrap navin"><div className="brand">Roasties</div><nav><a href="#ai">AI roast</a><a href="#crypto">Pay crypto</a></nav></div></header>
    <section className="hero wrap"><div className="glow" /><div className="badge">Pay 1 USDT. Get an AI roast.</div><h1>One brutally useful AI sentence for $1.</h1><p>Send a landing page URL and a USDT TRC20 payment hash. AI verifies payment, reads the page, and emails one sharp conversion fix.</p><div className="cta"><a className="btn dark" href="#ai">Get AI roast</a><a className="btn" href="#crypto">Wallet address</a></div><div className="proof">Manual price. Automated reply. USDT TRC20 only.</div></section>
    <section className="wrap grid"><div className="card"><div className="k blue">01 / pay</div><h3>Send 1 USDT</h3><p>Use TRC20 / Tron only and copy the transaction hash after payment.</p></div><div className="card"><div className="k pink">02 / submit</div><h3>Paste tx hash</h3><p>The backend checks receiver, amount, token, and duplicate usage.</p></div><div className="card"><div className="k red">03 / receive</div><h3>AI emails the roast</h3><p>You get one concise, specific fix for your landing page.</p></div></section>
    <section id="ai" className="section"><div className="wrap split"><div><h2>Get your AI roast.</h2><p>After sending 1 USDT TRC20, submit this form. If payment is valid, the AI reply is emailed automatically.</p><p className="small">Do not submit exchange withdrawal IDs. Use the actual Tron transaction hash.</p></div><form className="card form" action="/api/verify-and-roast" method="post"><label>Your email<input className="input" name="email" type="email" required placeholder="you@example.com" /></label><label>Landing page URL<input className="input" name="landingPageUrl" type="url" required placeholder="https://example.com" /></label><label>USDT TRC20 tx hash<input className="input" name="txHash" required placeholder="64-character transaction hash" /></label><button className="btn dark" type="submit">Verify payment + send AI roast</button><p className="small">If JavaScript is disabled, the raw API response appears after submit.</p></form></div></section>
    <section id="crypto" className="section"><div className="wrap split"><div><h2>Pay with crypto.</h2><p>Send <strong>1 USDT</strong> on <strong>TRC20 / Tron</strong> to this wallet.</p><p className="small">Use TRC20 only. Wrong-network transfers can be lost.</p></div><div className="card"><div className="k blue">USDT TRC20 wallet</div><div className="wallet">TBBR3P7L6F9Ta8miznGpEnF9emX9xqDLLr</div><p className="small">After payment, copy your transaction hash and submit the form above.</p></div></div></section>
    <section className="section"><div className="wrap split"><div><h2>Examples of output.</h2><ul><li>“Your headline describes the tool, not the buyer’s outcome; replace it with the concrete result they get in the first week.”</li><li>“Your first screen has three competing CTAs; make one dominant button and move the rest below the fold.”</li></ul></div><div className="terminal"><span className="line blue">$ automation</span><span className="line">verify USDT TRC20</span><span className="line">prevent duplicate tx hash</span><span className="line">fetch landing page text</span><span className="line pink">OpenAI writes the roast</span><span className="line red">email customer + owner</span></div></div></section>
  </main>;
}
